### ISSUE TITLE
How can I use netcoreapp2.0 instead of netcoreapp1.0?

### ISSUE THREAD

**Issue by oscarvarto** [TheAngryByrd/dotnet-mono#14]
Is it possible/easy?

All this is still pretty new and confusing to me: https://docs.microsoft.com/en-us/dotnet/standard/net-standard

See my attempts here:
https://github.com/dotnet/docs/issues/3180

**Comment by oscarvarto** [comment]
Do I even need netcoreapp1.0 installed if I want the example to run with mono?

In that case, what do I have to install from here? Everything?
https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.0.5-download.md

**Comment by TheAngryByrd** [comment]
Hmm, interesting.  Thanks for bringing to to my attention.  I'll have to do some research on how tools should support netstandard1.0 vs 2.0.

**Comment by TheAngryByrd** [comment]
This should be solved with https://github.com/TheAngryByrd/dotnet-mono/pull/15 . 
 Use the `0.2.0-alpha001` to test https://www.nuget.org/packages/dotnet-mono/0.2.0-alpha001
