### ISSUE TITLE
Is it possible just `dotnet build`?

### ISSUE THREAD

**Issue by netpyoung** [TheAngryByrd/dotnet-mono#22]
I really happy to found dotnet-mono.
but when i using that, i need to just `dotnet build` for build library.

**Comment by TheAngryByrd** [comment]
You should just be able to `dotnet build` but you may need to run `export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/` before to build for net45-net462.

**Comment by netpyoung** [comment]
I know dotnet-mono intend to run app resolving FrameworkPathOverride.
and 

```
export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
```

In my option, It will be better for add option just for build.
